/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/AppFooter.vue')['default']
    AppHeader: typeof import('./../components/AppHeader.vue')['default']
    DisplayError: typeof import('./../components/state/DisplayError.vue')['default']
    ErrorNotification: typeof import('./../components/ErrorNotification.vue')['default']
    LoadingSpinner: typeof import('./../components/state/LoadingSpinner.vue')['default']
    MessagesDisplay: typeof import('./../components/MessagesDisplay.vue')['default']
    PersistentIconPopup: typeof import('./../components/PersistentIconPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterLinkUp: typeof import('./../components/RouterLinkUp.vue')['default']
    RouterView: typeof import('vue-router')['RouterView']
    TailwindEmptyState: typeof import('./../components/state/tailwind-empty-state.vue')['default']
    ThemeSwitch: typeof import('./../components/ThemeSwitch.vue')['default']
  }
}
